sudo: required

services:
  - docker

language: python

python: 3.6

env:
  - TOX_ENV=py36

#before_install:
  #- docker-compose -f up --build -d
  #- #docker -v

script:
  - tox -e $TOX_ENV
  - sh tests/test_docker.sh

install:
  - pip install autopep8
  - pip install cookiecutter
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
